import test from 'node:test';
import assert from 'node:assert/strict';
globalThis.window = { NEXORA_CONFIG: { supabaseUrl: 'https://demo.supabase.co', supabasePublishableKey: 'sb_publishable_test' } };
const api = await import('../js/api.js');
const { mountDatabaseControls } = await import('../js/auth-ui.js');
test('content stays hidden on failed login and hides immediately during sign-out', async () => {
  const elements = new Map();
  const element = () => ({ hidden: false, textContent: '', disabled: false, listeners: {}, addEventListener(name, fn) { this.listeners[name] = fn; } });
  for (const id of ['database-controls', 'database-status', 'database-signin', 'database-signout', 'database-refresh', 'database-auth-message', 'signin-heading', 'signin-intro']) elements.set(id, element());
  const form = elements.get('database-signin');
  form.elements = { email: { value: 'staff@example.test' }, password: { value: 'test-only-password' } };
  const content = [element(), element()];
  const buttons = [elements.get('database-signout'), elements.get('database-refresh')];
  elements.get('database-controls').querySelectorAll = () => buttons;
  globalThis.document = { getElementById: id => elements.get(id), querySelectorAll: () => content, body: { classList: { toggle() {} } } };
  let loginAllowed = false;
  let finishLogout;
  globalThis.fetch = async url => {
    if (url.includes('/auth/v1/token')) return { ok: loginAllowed, status: 400, json: async () => ({ access_token: 'test-jwt', refresh_token: 'test-refresh', expires_in: 3600 }) };
    if (url.includes('/auth/v1/logout')) return new Promise(resolve => { finishLogout = () => resolve({ ok: true }); });
    return { ok: true, json: async () => url.includes('frontend_units_v') ? [{ id: 'unit' }] : [] };
  };
  mountDatabaseControls(() => {});
  assert.ok(content.every(el => el.hidden));
  await form.listeners.submit({ preventDefault() {} });
  assert.ok(content.every(el => el.hidden));
  assert.equal(api.isSignedIn(), false);
  loginAllowed = true;
  form.elements.password.value = 'test-only-password';
  await form.listeners.submit({ preventDefault() {} });
  assert.ok(content.every(el => !el.hidden));
  assert.equal(form.elements.password.value, '');
  const loggingOut = elements.get('database-signout').listeners.click();
  assert.ok(content.every(el => el.hidden));
  assert.equal(api.isSignedIn(), false);
  finishLogout();
  await loggingOut;
  assert.ok(content.every(el => el.hidden));
});
